### ISSUE TITLE
Nested properties not generating primary key  

### ISSUE THREAD

**Issue by vickydeJager** [louisevanderlith/Lith.DocStore#1]
{  
   "Name":"test",
   "RegistrationNo":"1234",
   "Address":{  
      "StreetNo":"1234",
      "Street":"asdfgh",
      "UnitNo":"123",
      "EstateName":"ASDFGH",
      "Suburb":"fghjk",
      "City":"dfghj",
      "Province":"fghj",
      "PostalCode":"2345",
      "Coordinates":"",
      "Type":0,
      "ID":"00000000-0000-0000-0000-000000000000",
      "DateCreated":"0001-01-01T00:00:00",
      "IsDeleted":false
   },
   "ContactDetails":[  
      {  
         "ContactType":0,
         "Value":"123456789",
         "IsActive":true,
         "ID":"00000000-0000-0000-0000-000000000000",
         "DateCreated":"0001-01-01T00:00:00",
         "IsDeleted":false
      },
      {  
         "ContactType":2,
         "Value":"srgdg@dff.com",
         "IsActive":true,
         "ID":"00000000-0000-0000-0000-000000000000",
         "DateCreated":"0001-01-01T00:00:00",
         "IsDeleted":false
      }
   ],
   "LogoID":"31403825-040d-47d5-8b99-227f1aefa1b0",
   "Clients":null,
   "Quotes":null,
   "ID":"07f10623-22dd-4e93-be43-5d75d9fb544e",
   "DateCreated":"2018-03-14T21:01:22.8928545+02:00",
   "IsDeleted":false
}

**Comment by louisevanderlith** [comment]
Fixed and Merged
